### ISSUE TITLE
No boulders makes Sokoban impossible?

### ISSUE THREAD

**Issue by Litostorg** [SLASHEM-Extended/SLASHEM-Extended#1]
First time i've done this, so not sure if this is the best place to post. But loving your fork of Slash'EM.

I'm currently playing a character and got to the Sokoban level and realised that the item the game can't generate is a boulder, so making it impossible(??) to complete.
P.S.
Is there anyway round this (will enough scrolls of earth work, or is there no way for a boulder to be created)? It's not a big deal as i have a BOH already but wondered if this was within the acceptable limits of making the game harder etc. (personally i don't mind it's kinda neat/amusing).

**Comment by AmyBSOD** [comment]
Hi, and thanks for giving this fork a try! :) I've not expected this to happen, but I also think it's quite neat; scrolls/wands of trap disarming will see you through, although they're kinda rare so it's unlikely to find enough of them. Unfortunately, methods of boulder creation will now be completely unable to generate boulders in your game. But yeah, if you already have a BoH then it's not really necessary to get to the prize.

**Comment by Litostorg** [comment]
Thanks for the quick update, i'll carry on regardless then :).

**Comment by AmyBSOD** [comment]
It might be worth noting that if this happens in a sokosolver game, the game will simply ignore that boulders cannot exist, and spawn them anyway. This is because in sokosolver mode the entire dungeon is made up of sokoban levels and the player has to traverse them. But for everyone else, Sokoban is only a non-mandatory side dungeon, meaning that occasionally you can get unlucky to have boulders not spawn there and then you have to deal with it ;)
