### ISSUE TITLE
Game crash on monster level teleporting me

### ISSUE THREAD

**Issue by Litostorg** [SLASHEM-Extended/SLASHEM-Extended#2]
Hi again. Had Version 1.3.7 crash when a monster level teleported me. Recover worked fine, but wondered if 
a) the error file is any use to you and the best way to send it over [given it appears to be binary, i can't upload it here unless i can just hack the extension].
b) Is any other info benefical, like previous save (not sure how recent tho)?

Thanks.

**Comment by AmyBSOD** [comment]
Thanks for the report; this error is known, and should be fixed in version 1.3.9. The cause was the monster still being processed after the player was levelported away, and since the player was moved to another dungeon level the monster in question was no longer "in memory" so to speak, so the game tried to reference an invalid monster. So you can keep playing but I'd advise you to update after your current game is done. :-)

**Comment by Litostorg** [comment]
Ok, many thanks for the update and fix :).
