### ISSUE TITLE
New README?

### ISSUE THREAD

**Issue by MetaNite64** [SLASHEM-Extended/SLASHEM-Extended#31]
This is NOT an issue, I just didn't quite know where else to put this. I was wondering if I could possibly write up a new README for this repository, because the current is just forked from Nethack 3.4.3. I think it would make it a lot easier for people to figure out how to install/start playing this game, and make it seem more independent from Nethack. Of course, you could write it yourself, but I currently have tons of free time and am willing to spend the time writing it up. Either way, thanks!

**Comment by AmyBSOD** [comment]
Uhh I guess I forgot to answer, sorry :) Anyway, you're free to write one, and then I'll decide whether I want to use it (and maybe add to it) :D

**Comment by MetaNite64** [comment]
No problem at all. I’ll see if I can get on it this weekend.

**Comment by MetaNite64** [comment]
I have the readme done, but I can't figure out how to push the new branch I made to github, so I'll just link the file (in txt form): [README.txt](https://github.com/SLASHEM-Extended/SLASHEM-Extended/files/3672895/README.txt)

**Comment by AmyBSOD** [comment]
Alright I added it in https://github.com/SLASHEM-Extended/SLASHEM-Extended/commit/be32bbb77633ae516e2a4cb5314ffe265f52e67e - had to add some of my own comments though, especially since players could be using Windows where all those unix-specific instructions would seem very confusing (we have to assume a user that knows basically nothing about computers, who will try "sudo apt-get foo bar" on Windows and be surprised when it results in an error message!) ;)

**Comment by MetaNite64** [comment]
Thanks. I totally forgot about Windows instructions, and anyway, I wouldn't be able to test it since the only Windows computers in the house are either severely broken or only for work.
