### ISSUE TITLE
Riding A Mount Engulfing A Monster Problem?

### ISSUE THREAD

**Issue by Litostorg** [SLASHEM-Extended/SLASHEM-Extended#32]
Hi,

I'm on an old version of SlashEm Extended (v2.0) from 2017 and I'm riding a Mount that got polymorphed into a Vortex Lord, which I'm still riding, which then has swallowed two different monsters and both times I've got the 
placing steed onto map?
Program in disorder...
The xyz is regurgiated!  placing steed onto map?
Program in disorder...

I've attached the save file, but are bug reports from old versions of the game actually any use?

P.S.
Thanks again for producing a really entertaining version :).
![MountSwallowingSomethingElse1](https://user-images.githubusercontent.com/7272873/63294206-a25d2200-c2c1-11e9-9dfa-10ee5d7ec4f4.jpg)
[SwallowingMountBug.zip](https://github.com/SLASHEM-Extended/SLASHEM-Extended/files/3517385/SwallowingMountBug.zip)

**Comment by AmyBSOD** [comment]
Hi again, IIRC I read from you before? Please don't keep old versions around, the bug is fixed in newer versions. Sending savegame files does me no good either because version updates happen often and unless I specifically request the savegame file, I probably won't have the old version around to load it. If you need to finish that old game, you can either use a different steed or you'll unfortunately have to live with the error message spam (and then obviously update the game to at least 2.50). Sorry. Anyway, thanks for your continued interest in this variant and I hope you'll enjoy the new version! :)
