### ISSUE TITLE
Underscore Algorithm Slightly Broken

### ISSUE THREAD

**Issue by MetaNite64** [SLASHEM-Extended/SLASHEM-Extended#34]
While playing through a great game, I underscored over to the downstairs in the first level of the Gnomish Mines. Instead of taking me straight there, it moved me straight into a wall. I tried searching that wall, and there were no secret passages. It's only a minor inconvenience, but it bothered me. This shouldn't be a first priority.

**Comment by AmyBSOD** [comment]
There probably was a trap or something in the way of the direct path, vanilla behavior :P (since I can't see your map, I can't confirm this suspicion, but that would probably be it). Also, the underscore algorithm certainly doesn't leak information about secret passages even if they were there; if you underscore-move somewhere, it treats undiscovered secret passages as obstacles.
