### ISSUE TITLE
Traps can suck you into walls

### ISSUE THREAD

**Issue by oddhack** [SLASHEM-Extended/SLASHEM-Extended#37]
Attempting to untrap traps embedded in walls can suck you into the walls. Following a bear trap to a dart trap, I ended up in solid rock. Not sure it makes a lot of sense to have a trap in a wall that can actually affect you before the wall is dug out, but it is an amusing interaction in any case.

**Comment by AmyBSOD** [comment]
Yeah, obviously not a bug but a feature :) If you get stuck in the wall and can't dig, use the phase door technique/scroll. Just be careful on levels with undiggable walls, because those might force you to wait until you randomly get the "a portal to the void opens, do you want to step through and teleport to a random location" or whatever the exact wording was (that exists specifically for the purpose of letting one continue the game when stuck).
