### ISSUE TITLE
Warning: Low Local Memory. Freeing description strings.

### ISSUE THREAD

**Issue by MetaNite64** [SLASHEM-Extended/SLASHEM-Extended#41]
Playing on the esm server, I noticed that the message in the title would pop up instead of whatever message was supposed to appear. Eventually it appeared every time my character moved, and the character onscreen froze in place. It even replaced the save game prompt, though it still worked fine. I have no clue what's happening with this. It doesn't crash anything, although the frozen character is pretty annoying. I have a picture of the message, although no video yet:
![image](https://user-images.githubusercontent.com/32368758/76144604-b1ca6f80-6047-11ea-81a0-6771e39e3c56.png)

**Comment by AmyBSOD** [comment]
You probably triggered a nasty trap. Works as intended. I didn't watch your game so I don't know what exactly you mean by "character frozen in place", but chances are there was a prompt being displayed (and replaced by the low local memory message) and you'd have had to answer it in some way, perhaps by spelling out "yes" or "no", recognizable by the fact that the cursor is at the "Low Local Memory" message instead of on your character.
